version: "3.8"
services:
  db:
    container_name: db
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    env_file:
      - .db.env
    networks:
      - net

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    networks:
      - net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env
    networks:
      - net
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db:

networks:
  net:
    driver: bridge
